name: Перевірка дублювань

on:
  pull_request:
    paths:
      - '**.txt'
      - 'check_duplicates.sh'
      - '.github/workflows/duplicate_check.yml'

jobs:
  duplicates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Виконати перевірку
        run: |
          chmod +x ./check_duplicates.sh
          ./check_duplicates.sh
